### PR TITLE
feat: additional environment variables config option

### PR DESCRIPTION
**Pull request by Ninjdai1**
Adds an optional config option for additional environment variables to be passed to launched servers
Example use case: passing credentials and addresses for a database

### CODE REVIEW

**Comment by antndev** [comment]
did you test it?

**Comment by antndev** [comment]
The idea is good, but please modify it to split the environment variables from the cinfig with a ","and, for each, add a -e argument in the Docker run command to make it work.

**Comment by antndev** [comment]
An example from a startup cmd:

sudo docker run -d -t -i -e REDIS_NAMESPACE='staging' \ 
-e POSTGRES_ENV_POSTGRES_PASSWORD='foo' \
-e POSTGRES_ENV_POSTGRES_USER='bar' \
-e POSTGRES_ENV_DB_NAME='mysite_staging' \
-e POSTGRES_PORT_5432_TCP_ADDR='docker-db-1.hidden.us-east-1.rds.amazonaws.com' \
-e SITE_URL='staging.mysite.com' \
-p 80:80 \
--link redis:redis \  
--name container_name dockerhub_id/image_name

**Comment by Ninjdai1** [comment]
Tested and works properly:
`[20:02:29 INFO]: docker run -d -e PAPER_VELOCITY_SECRET=xxxxxxxxxxx  -e FOO=bar -e FOO2=bar2 -p 44451:25
565 --name Lobby-qtvat-example ninjdai/splatcube-lobby:latest`

**Pull request merged**
